#!/usr/bin/env node
/**
 * Install git pre-commit hook to build performed/index.json and stage it.
 */
const fs = require('fs');
const path = require('path');

function main() {
  const repoRoot = path.resolve(__dirname, '..');
  const gitDir = path.join(repoRoot, '.git');
  const hooksDir = path.join(gitDir, 'hooks');
  if (!fs.existsSync(gitDir)) {
    console.error('Not a git repository:', repoRoot);
    process.exit(1);
  }
  if (!fs.existsSync(hooksDir)) fs.mkdirSync(hooksDir);
  const hookPath = path.join(hooksDir, 'pre-commit');
  const relNode = process.env.NODE || 'node';
  const script = `#!/bin/sh
# Auto-generated by scripts/install-hooks.js
# Build local performed index and stage it so History works offline
${relNode} scripts/build_performed_index.js 1>/dev/null 2>&1 || exit 1
if [ -f performed/index.json ]; then
  git add performed/index.json
fi
`;
  fs.writeFileSync(hookPath, script, { mode: 0o755 });
  console.log('Installed pre-commit hook at', hookPath);
}

main();
