name: Validate Markdown & Schemas

on:
  push:
    branches: [ main, feature/**, fix/** ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema

      - name: Validate Markdown links
        run: python3 scripts/validate_links.py

      - name: Validate schemas
        run: python3 scripts/validate_schemas.py
